node1:
  hostname: node1
  volumes:
    - ./src:/src
  build: .
  restart: unless-stopped
  ports:
    - "8080:80"
  expose:
    - 80

node2:
  hostname: node2
  volumes:
    - ./src:/src
  build: .
  restart: unless-stopped
  ports:
    - "8081:80"
  expose:
    - 80

node3:
  hostname: node3  
  volumes:
    - ./src:/src
  build: .
  restart: unless-stopped
  ports:
    - "8082:80"
  expose:
    - 80

haproxy:
  image: eeacms/haproxy
  links:
    - node1
    - node2
    - node3
  volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  ports:
    - "80:80"
    - "1936:1936"
  expose:
    - "80"
    - "1936"